// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArgoCDApplicationTemplateLister helps list ArgoCDApplicationTemplates.
// All objects returned here must be treated as read-only.
type ArgoCDApplicationTemplateLister interface {
	// List lists all ArgoCDApplicationTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.ArgoCDApplicationTemplate, err error)
	// Get retrieves the ArgoCDApplicationTemplate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.ArgoCDApplicationTemplate, error)
	ArgoCDApplicationTemplateListerExpansion
}

// argoCDApplicationTemplateLister implements the ArgoCDApplicationTemplateLister interface.
type argoCDApplicationTemplateLister struct {
	listers.ResourceIndexer[*storagev1.ArgoCDApplicationTemplate]
}

// NewArgoCDApplicationTemplateLister returns a new ArgoCDApplicationTemplateLister.
func NewArgoCDApplicationTemplateLister(indexer cache.Indexer) ArgoCDApplicationTemplateLister {
	return &argoCDApplicationTemplateLister{listers.New[*storagev1.ArgoCDApplicationTemplate](indexer, storagev1.Resource("argocdapplicationtemplate"))}
}
