// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkEnvironmentLister helps list NetworkEnvironments.
// All objects returned here must be treated as read-only.
type NetworkEnvironmentLister interface {
	// List lists all NetworkEnvironments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.NetworkEnvironment, err error)
	// Get retrieves the NetworkEnvironment from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.NetworkEnvironment, error)
	NetworkEnvironmentListerExpansion
}

// networkEnvironmentLister implements the NetworkEnvironmentLister interface.
type networkEnvironmentLister struct {
	listers.ResourceIndexer[*storagev1.NetworkEnvironment]
}

// NewNetworkEnvironmentLister returns a new NetworkEnvironmentLister.
func NewNetworkEnvironmentLister(indexer cache.Indexer) NetworkEnvironmentLister {
	return &networkEnvironmentLister{listers.New[*storagev1.NetworkEnvironment](indexer, storagev1.Resource("networkenvironment"))}
}
