// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OSImageLister helps list OSImages.
// All objects returned here must be treated as read-only.
type OSImageLister interface {
	// List lists all OSImages in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.OSImage, err error)
	// Get retrieves the OSImage from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.OSImage, error)
	OSImageListerExpansion
}

// oSImageLister implements the OSImageLister interface.
type oSImageLister struct {
	listers.ResourceIndexer[*storagev1.OSImage]
}

// NewOSImageLister returns a new OSImageLister.
func NewOSImageLister(indexer cache.Indexer) OSImageLister {
	return &oSImageLister{listers.New[*storagev1.OSImage](indexer, storagev1.Resource("osimage"))}
}
