// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SSHKeyLister helps list SSHKeys.
// All objects returned here must be treated as read-only.
type SSHKeyLister interface {
	// List lists all SSHKeys in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.SSHKey, err error)
	// Get retrieves the SSHKey from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.SSHKey, error)
	SSHKeyListerExpansion
}

// sSHKeyLister implements the SSHKeyLister interface.
type sSHKeyLister struct {
	listers.ResourceIndexer[*storagev1.SSHKey]
}

// NewSSHKeyLister returns a new SSHKeyLister.
func NewSSHKeyLister(indexer cache.Indexer) SSHKeyLister {
	return &sSHKeyLister{listers.New[*storagev1.SSHKey](indexer, storagev1.Resource("sshkey"))}
}
