// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TenantLister helps list Tenants.
// All objects returned here must be treated as read-only.
type TenantLister interface {
	// List lists all Tenants in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.Tenant, err error)
	// Get retrieves the Tenant from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.Tenant, error)
	TenantListerExpansion
}

// tenantLister implements the TenantLister interface.
type tenantLister struct {
	listers.ResourceIndexer[*storagev1.Tenant]
}

// NewTenantLister returns a new TenantLister.
func NewTenantLister(indexer cache.Indexer) TenantLister {
	return &tenantLister{listers.New[*storagev1.Tenant](indexer, storagev1.Resource("tenant"))}
}
