// Code generated by client-gen. DO NOT EDIT.

package v1

type AnnouncementExpansion interface{}

type ClusterExpansion interface{}

type ClusterAccountTemplateExpansion interface{}

type ClusterConnectExpansion interface{}

type ClusterRoleExpansion interface{}

type ConfigExpansion interface{}

type FeatureExpansion interface{}

type LicenseExpansion interface{}

type LicenseTokenExpansion interface{}

type LoftUpgradeExpansion interface{}

type SelfSubjectAccessReviewExpansion interface{}

type SharedSecretExpansion interface{}

type SubjectAccessReviewExpansion interface{}

type TeamExpansion interface{}

type UserExpansion interface{}
