// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/loft-sh/api/v4/pkg/apis/management/v1"
	scheme "github.com/loft-sh/api/v4/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	gentype "k8s.io/client-go/gentype"
)

// ConnectorsGetter has a method to return a ConnectorInterface.
// A group's client should implement this interface.
type ConnectorsGetter interface {
	Connectors() ConnectorInterface
}

// ConnectorInterface has methods to work with Connector resources.
type ConnectorInterface interface {
	Create(ctx context.Context, connector *managementv1.Connector, opts metav1.CreateOptions) (*managementv1.Connector, error)
	Update(ctx context.Context, connector *managementv1.Connector, opts metav1.UpdateOptions) (*managementv1.Connector, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.Connector, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.ConnectorList, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.Connector, err error)
	ConnectorExpansion
}

// connectors implements ConnectorInterface
type connectors struct {
	*gentype.ClientWithList[*managementv1.Connector, *managementv1.ConnectorList]
}

// newConnectors returns a Connectors
func newConnectors(c *ManagementV1Client) *connectors {
	return &connectors{
		gentype.NewClientWithList[*managementv1.Connector, *managementv1.ConnectorList](
			"connectors",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1.Connector { return &managementv1.Connector{} },
			func() *managementv1.ConnectorList { return &managementv1.ConnectorList{} },
		),
	}
}
