// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	clusterv1 "github.com/loft-sh/api/pkg/apis/cluster/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContexts implements ContextInterface
type FakeContexts struct {
	Fake *FakeClusterV1
}

var contextsResource = schema.GroupVersionResource{Group: "cluster.loft.sh", Version: "v1", Resource: "contexts"}

var contextsKind = schema.GroupVersionKind{Group: "cluster.loft.sh", Version: "v1", Kind: "Context"}

// Get takes name of the context, and returns the corresponding context object, and an error if there is any.
func (c *FakeContexts) Get(ctx context.Context, name string, options v1.GetOptions) (result *clusterv1.Context, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(contextsResource, name), &clusterv1.Context{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Context), err
}

// List takes label and field selectors, and returns the list of Contexts that match those selectors.
func (c *FakeContexts) List(ctx context.Context, opts v1.ListOptions) (result *clusterv1.ContextList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(contextsResource, contextsKind, opts), &clusterv1.ContextList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clusterv1.ContextList{ListMeta: obj.(*clusterv1.ContextList).ListMeta}
	for _, item := range obj.(*clusterv1.ContextList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested contexts.
func (c *FakeContexts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(contextsResource, opts))
}

// Create takes the representation of a context and creates it.  Returns the server's representation of the context, and an error, if there is any.
func (c *FakeContexts) Create(ctx context.Context, context *clusterv1.Context, opts v1.CreateOptions) (result *clusterv1.Context, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(contextsResource, context), &clusterv1.Context{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Context), err
}

// Update takes the representation of a context and updates it. Returns the server's representation of the context, and an error, if there is any.
func (c *FakeContexts) Update(ctx context.Context, context *clusterv1.Context, opts v1.UpdateOptions) (result *clusterv1.Context, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(contextsResource, context), &clusterv1.Context{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Context), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeContexts) UpdateStatus(ctx context.Context, context *clusterv1.Context, opts v1.UpdateOptions) (*clusterv1.Context, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(contextsResource, "status", context), &clusterv1.Context{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Context), err
}

// Delete takes name of the context and deletes it. Returns an error if one occurs.
func (c *FakeContexts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(contextsResource, name), &clusterv1.Context{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContexts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(contextsResource, listOpts)

	_, err := c.Fake.Invokes(action, &clusterv1.ContextList{})
	return err
}

// Patch applies the patch and returns the patched context.
func (c *FakeContexts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clusterv1.Context, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(contextsResource, name, pt, data, subresources...), &clusterv1.Context{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Context), err
}
