// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	managementv1 "github.com/loft-sh/api/v4/pkg/apis/management/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArgoCDApplicationLister helps list ArgoCDApplications.
// All objects returned here must be treated as read-only.
type ArgoCDApplicationLister interface {
	// List lists all ArgoCDApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.ArgoCDApplication, err error)
	// ArgoCDApplications returns an object that can list and get ArgoCDApplications.
	ArgoCDApplications(namespace string) ArgoCDApplicationNamespaceLister
	ArgoCDApplicationListerExpansion
}

// argoCDApplicationLister implements the ArgoCDApplicationLister interface.
type argoCDApplicationLister struct {
	listers.ResourceIndexer[*managementv1.ArgoCDApplication]
}

// NewArgoCDApplicationLister returns a new ArgoCDApplicationLister.
func NewArgoCDApplicationLister(indexer cache.Indexer) ArgoCDApplicationLister {
	return &argoCDApplicationLister{listers.New[*managementv1.ArgoCDApplication](indexer, managementv1.Resource("argocdapplication"))}
}

// ArgoCDApplications returns an object that can list and get ArgoCDApplications.
func (s *argoCDApplicationLister) ArgoCDApplications(namespace string) ArgoCDApplicationNamespaceLister {
	return argoCDApplicationNamespaceLister{listers.NewNamespaced[*managementv1.ArgoCDApplication](s.ResourceIndexer, namespace)}
}

// ArgoCDApplicationNamespaceLister helps list and get ArgoCDApplications.
// All objects returned here must be treated as read-only.
type ArgoCDApplicationNamespaceLister interface {
	// List lists all ArgoCDApplications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.ArgoCDApplication, err error)
	// Get retrieves the ArgoCDApplication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*managementv1.ArgoCDApplication, error)
	ArgoCDApplicationNamespaceListerExpansion
}

// argoCDApplicationNamespaceLister implements the ArgoCDApplicationNamespaceLister
// interface.
type argoCDApplicationNamespaceLister struct {
	listers.ResourceIndexer[*managementv1.ArgoCDApplication]
}
