// Code generated by client-gen. DO NOT EDIT.

package v1

type AccessKeyExpansion interface{}

type AppExpansion interface{}

type ClusterExpansion interface{}

type ClusterAccessExpansion interface{}

type ClusterAccountTemplateExpansion interface{}

type ClusterRoleTemplateExpansion interface{}

type SharedSecretExpansion interface{}

type SpaceConstraintExpansion interface{}

type SpaceTemplateExpansion interface{}

type TaskExpansion interface{}

type TeamExpansion interface{}

type UserExpansion interface{}

type VirtualClusterTemplateExpansion interface{}
