// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRunners implements RunnerInterface
type FakeRunners struct {
	Fake *FakeStorageV1
}

var runnersResource = schema.GroupVersionResource{Group: "storage.loft.sh", Version: "v1", Resource: "runners"}

var runnersKind = schema.GroupVersionKind{Group: "storage.loft.sh", Version: "v1", Kind: "Runner"}

// Get takes name of the runner, and returns the corresponding runner object, and an error if there is any.
func (c *FakeRunners) Get(ctx context.Context, name string, options v1.GetOptions) (result *storagev1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(runnersResource, name), &storagev1.Runner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.Runner), err
}

// List takes label and field selectors, and returns the list of Runners that match those selectors.
func (c *FakeRunners) List(ctx context.Context, opts v1.ListOptions) (result *storagev1.RunnerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(runnersResource, runnersKind, opts), &storagev1.RunnerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &storagev1.RunnerList{ListMeta: obj.(*storagev1.RunnerList).ListMeta}
	for _, item := range obj.(*storagev1.RunnerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runners.
func (c *FakeRunners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(runnersResource, opts))
}

// Create takes the representation of a runner and creates it.  Returns the server's representation of the runner, and an error, if there is any.
func (c *FakeRunners) Create(ctx context.Context, runner *storagev1.Runner, opts v1.CreateOptions) (result *storagev1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(runnersResource, runner), &storagev1.Runner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.Runner), err
}

// Update takes the representation of a runner and updates it. Returns the server's representation of the runner, and an error, if there is any.
func (c *FakeRunners) Update(ctx context.Context, runner *storagev1.Runner, opts v1.UpdateOptions) (result *storagev1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(runnersResource, runner), &storagev1.Runner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.Runner), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRunners) UpdateStatus(ctx context.Context, runner *storagev1.Runner, opts v1.UpdateOptions) (*storagev1.Runner, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(runnersResource, "status", runner), &storagev1.Runner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.Runner), err
}

// Delete takes name of the runner and deletes it. Returns an error if one occurs.
func (c *FakeRunners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(runnersResource, name, opts), &storagev1.Runner{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRunners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(runnersResource, listOpts)

	_, err := c.Fake.Invokes(action, &storagev1.RunnerList{})
	return err
}

// Patch applies the patch and returns the patched runner.
func (c *FakeRunners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *storagev1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(runnersResource, name, pt, data, subresources...), &storagev1.Runner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.Runner), err
}
