// Code generated by client-gen. DO NOT EDIT.

package v1

type AnnouncementExpansion interface{}

type AppExpansion interface{}

type ClusterExpansion interface{}

type ClusterAccessExpansion interface{}

type ClusterAccountTemplateExpansion interface{}

type ClusterConnectExpansion interface{}

type ClusterRoleTemplateExpansion interface{}

type ConfigExpansion interface{}

type DirectClusterEndpointTokenExpansion interface{}

type EventExpansion interface{}

type FeatureExpansion interface{}

type LicenseExpansion interface{}

type LicenseTokenExpansion interface{}

type LoftUpgradeExpansion interface{}

type OwnedAccessKeyExpansion interface{}

type PolicyViolationExpansion interface{}

type ResetAccessKeyExpansion interface{}

type SelfExpansion interface{}

type SelfSubjectAccessReviewExpansion interface{}

type SharedSecretExpansion interface{}

type SpaceConstraintExpansion interface{}

type SpaceTemplateExpansion interface{}

type SubjectAccessReviewExpansion interface{}

type TaskExpansion interface{}

type TeamExpansion interface{}

type UserExpansion interface{}

type VirtualClusterTemplateExpansion interface{}
