// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/api/v4/pkg/apis/management/v1"
	managementv1 "github.com/loft-sh/api/v4/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTenants implements TenantInterface
type fakeTenants struct {
	*gentype.FakeClientWithList[*v1.Tenant, *v1.TenantList]
	Fake *FakeManagementV1
}

func newFakeTenants(fake *FakeManagementV1) managementv1.TenantInterface {
	return &fakeTenants{
		gentype.NewFakeClientWithList[*v1.Tenant, *v1.TenantList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("tenants"),
			v1.SchemeGroupVersion.WithKind("Tenant"),
			func() *v1.Tenant { return &v1.Tenant{} },
			func() *v1.TenantList { return &v1.TenantList{} },
			func(dst, src *v1.TenantList) { dst.ListMeta = src.ListMeta },
			func(list *v1.TenantList) []*v1.Tenant { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.TenantList, items []*v1.Tenant) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
