// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/api/v4/pkg/apis/management/v1"
	managementv1 "github.com/loft-sh/api/v4/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVirtualClusterConnections implements VirtualClusterConnectionInterface
type fakeVirtualClusterConnections struct {
	*gentype.FakeClient[*v1.VirtualClusterConnection]
	Fake *FakeManagementV1
}

func newFakeVirtualClusterConnections(fake *FakeManagementV1) managementv1.VirtualClusterConnectionInterface {
	return &fakeVirtualClusterConnections{
		gentype.NewFakeClient[*v1.VirtualClusterConnection](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("virtualclusterconnections"),
			v1.SchemeGroupVersion.WithKind("VirtualClusterConnection"),
			func() *v1.VirtualClusterConnection { return &v1.VirtualClusterConnection{} },
		),
		fake,
	}
}
