// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1 "github.com/loft-sh/api/v4/pkg/apis/management/v1"
	managementv1 "github.com/loft-sh/api/v4/pkg/clientset/versioned/typed/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeExternalCredentials implements ExternalCredentialInterface
type fakeExternalCredentials struct {
	*gentype.FakeClientWithList[*v1.ExternalCredential, *v1.ExternalCredentialList]
	Fake *FakeManagementV1
}

func newFakeExternalCredentials(fake *FakeManagementV1, namespace string) managementv1.ExternalCredentialInterface {
	return &fakeExternalCredentials{
		gentype.NewFakeClientWithList[*v1.ExternalCredential, *v1.ExternalCredentialList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("externalcredentials"),
			v1.SchemeGroupVersion.WithKind("ExternalCredential"),
			func() *v1.ExternalCredential { return &v1.ExternalCredential{} },
			func() *v1.ExternalCredentialList { return &v1.ExternalCredentialList{} },
			func(dst, src *v1.ExternalCredentialList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ExternalCredentialList) []*v1.ExternalCredential {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.ExternalCredentialList, items []*v1.ExternalCredential) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetCredentials takes name of the externalCredential, and returns the corresponding externalCredentialCredentials object, and an error if there is any.
func (c *fakeExternalCredentials) GetCredentials(ctx context.Context, externalCredentialName string, options metav1.GetOptions) (result *v1.ExternalCredentialCredentials, err error) {
	emptyResult := &v1.ExternalCredentialCredentials{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "credentials", externalCredentialName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ExternalCredentialCredentials), err
}
