// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/loft-sh/api/v3/pkg/apis/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSpaceConstraints implements SpaceConstraintInterface
type FakeSpaceConstraints struct {
	Fake *FakeManagementV1
}

var spaceconstraintsResource = v1.SchemeGroupVersion.WithResource("spaceconstraints")

var spaceconstraintsKind = v1.SchemeGroupVersion.WithKind("SpaceConstraint")

// Get takes name of the spaceConstraint, and returns the corresponding spaceConstraint object, and an error if there is any.
func (c *FakeSpaceConstraints) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(spaceconstraintsResource, name), &v1.SpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpaceConstraint), err
}

// List takes label and field selectors, and returns the list of SpaceConstraints that match those selectors.
func (c *FakeSpaceConstraints) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SpaceConstraintList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(spaceconstraintsResource, spaceconstraintsKind, opts), &v1.SpaceConstraintList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SpaceConstraintList{ListMeta: obj.(*v1.SpaceConstraintList).ListMeta}
	for _, item := range obj.(*v1.SpaceConstraintList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested spaceConstraints.
func (c *FakeSpaceConstraints) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(spaceconstraintsResource, opts))
}

// Create takes the representation of a spaceConstraint and creates it.  Returns the server's representation of the spaceConstraint, and an error, if there is any.
func (c *FakeSpaceConstraints) Create(ctx context.Context, spaceConstraint *v1.SpaceConstraint, opts metav1.CreateOptions) (result *v1.SpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(spaceconstraintsResource, spaceConstraint), &v1.SpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpaceConstraint), err
}

// Update takes the representation of a spaceConstraint and updates it. Returns the server's representation of the spaceConstraint, and an error, if there is any.
func (c *FakeSpaceConstraints) Update(ctx context.Context, spaceConstraint *v1.SpaceConstraint, opts metav1.UpdateOptions) (result *v1.SpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(spaceconstraintsResource, spaceConstraint), &v1.SpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpaceConstraint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSpaceConstraints) UpdateStatus(ctx context.Context, spaceConstraint *v1.SpaceConstraint, opts metav1.UpdateOptions) (*v1.SpaceConstraint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(spaceconstraintsResource, "status", spaceConstraint), &v1.SpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpaceConstraint), err
}

// Delete takes name of the spaceConstraint and deletes it. Returns an error if one occurs.
func (c *FakeSpaceConstraints) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(spaceconstraintsResource, name, opts), &v1.SpaceConstraint{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpaceConstraints) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(spaceconstraintsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SpaceConstraintList{})
	return err
}

// Patch applies the patch and returns the patched spaceConstraint.
func (c *FakeSpaceConstraints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(spaceconstraintsResource, name, pt, data, subresources...), &v1.SpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpaceConstraint), err
}
