// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	managementv1 "github.com/loft-sh/api/pkg/apis/management/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecrets implements SecretInterface
type FakeSecrets struct {
	Fake *FakeManagementV1
}

var secretsResource = schema.GroupVersionResource{Group: "management.loft.sh", Version: "v1", Resource: "secrets"}

var secretsKind = schema.GroupVersionKind{Group: "management.loft.sh", Version: "v1", Kind: "Secret"}

// Get takes name of the secret, and returns the corresponding secret object, and an error if there is any.
func (c *FakeSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *managementv1.Secret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(secretsResource, name), &managementv1.Secret{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.Secret), err
}

// List takes label and field selectors, and returns the list of Secrets that match those selectors.
func (c *FakeSecrets) List(ctx context.Context, opts v1.ListOptions) (result *managementv1.SecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(secretsResource, secretsKind, opts), &managementv1.SecretList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &managementv1.SecretList{ListMeta: obj.(*managementv1.SecretList).ListMeta}
	for _, item := range obj.(*managementv1.SecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secrets.
func (c *FakeSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(secretsResource, opts))
}

// Create takes the representation of a secret and creates it.  Returns the server's representation of the secret, and an error, if there is any.
func (c *FakeSecrets) Create(ctx context.Context, secret *managementv1.Secret, opts v1.CreateOptions) (result *managementv1.Secret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(secretsResource, secret), &managementv1.Secret{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.Secret), err
}

// Update takes the representation of a secret and updates it. Returns the server's representation of the secret, and an error, if there is any.
func (c *FakeSecrets) Update(ctx context.Context, secret *managementv1.Secret, opts v1.UpdateOptions) (result *managementv1.Secret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(secretsResource, secret), &managementv1.Secret{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.Secret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecrets) UpdateStatus(ctx context.Context, secret *managementv1.Secret, opts v1.UpdateOptions) (*managementv1.Secret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(secretsResource, "status", secret), &managementv1.Secret{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.Secret), err
}

// Delete takes name of the secret and deletes it. Returns an error if one occurs.
func (c *FakeSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(secretsResource, name), &managementv1.Secret{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(secretsResource, listOpts)

	_, err := c.Fake.Invokes(action, &managementv1.SecretList{})
	return err
}

// Patch applies the patch and returns the patched secret.
func (c *FakeSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementv1.Secret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(secretsResource, name, pt, data, subresources...), &managementv1.Secret{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.Secret), err
}
