// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/loft-sh/api/v3/pkg/apis/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterConnects implements ClusterConnectInterface
type FakeClusterConnects struct {
	Fake *FakeManagementV1
}

var clusterconnectsResource = v1.SchemeGroupVersion.WithResource("clusterconnects")

var clusterconnectsKind = v1.SchemeGroupVersion.WithKind("ClusterConnect")

// Get takes name of the clusterConnect, and returns the corresponding clusterConnect object, and an error if there is any.
func (c *FakeClusterConnects) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClusterConnect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterconnectsResource, name), &v1.ClusterConnect{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterConnect), err
}

// List takes label and field selectors, and returns the list of ClusterConnects that match those selectors.
func (c *FakeClusterConnects) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClusterConnectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterconnectsResource, clusterconnectsKind, opts), &v1.ClusterConnectList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ClusterConnectList{ListMeta: obj.(*v1.ClusterConnectList).ListMeta}
	for _, item := range obj.(*v1.ClusterConnectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterConnects.
func (c *FakeClusterConnects) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterconnectsResource, opts))
}

// Create takes the representation of a clusterConnect and creates it.  Returns the server's representation of the clusterConnect, and an error, if there is any.
func (c *FakeClusterConnects) Create(ctx context.Context, clusterConnect *v1.ClusterConnect, opts metav1.CreateOptions) (result *v1.ClusterConnect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterconnectsResource, clusterConnect), &v1.ClusterConnect{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterConnect), err
}

// Update takes the representation of a clusterConnect and updates it. Returns the server's representation of the clusterConnect, and an error, if there is any.
func (c *FakeClusterConnects) Update(ctx context.Context, clusterConnect *v1.ClusterConnect, opts metav1.UpdateOptions) (result *v1.ClusterConnect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterconnectsResource, clusterConnect), &v1.ClusterConnect{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterConnect), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterConnects) UpdateStatus(ctx context.Context, clusterConnect *v1.ClusterConnect, opts metav1.UpdateOptions) (*v1.ClusterConnect, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterconnectsResource, "status", clusterConnect), &v1.ClusterConnect{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterConnect), err
}

// Delete takes name of the clusterConnect and deletes it. Returns an error if one occurs.
func (c *FakeClusterConnects) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterconnectsResource, name, opts), &v1.ClusterConnect{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterConnects) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterconnectsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ClusterConnectList{})
	return err
}

// Patch applies the patch and returns the patched clusterConnect.
func (c *FakeClusterConnects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterConnect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterconnectsResource, name, pt, data, subresources...), &v1.ClusterConnect{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterConnect), err
}
