// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	managementv1 "github.com/loft-sh/api/v3/pkg/apis/management/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAgentAuditEvents implements AgentAuditEventInterface
type FakeAgentAuditEvents struct {
	Fake *FakeManagementV1
}

var agentauditeventsResource = schema.GroupVersionResource{Group: "management.loft.sh", Version: "v1", Resource: "agentauditevents"}

var agentauditeventsKind = schema.GroupVersionKind{Group: "management.loft.sh", Version: "v1", Kind: "AgentAuditEvent"}

// Get takes name of the agentAuditEvent, and returns the corresponding agentAuditEvent object, and an error if there is any.
func (c *FakeAgentAuditEvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *managementv1.AgentAuditEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(agentauditeventsResource, name), &managementv1.AgentAuditEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.AgentAuditEvent), err
}

// List takes label and field selectors, and returns the list of AgentAuditEvents that match those selectors.
func (c *FakeAgentAuditEvents) List(ctx context.Context, opts v1.ListOptions) (result *managementv1.AgentAuditEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(agentauditeventsResource, agentauditeventsKind, opts), &managementv1.AgentAuditEventList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &managementv1.AgentAuditEventList{ListMeta: obj.(*managementv1.AgentAuditEventList).ListMeta}
	for _, item := range obj.(*managementv1.AgentAuditEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested agentAuditEvents.
func (c *FakeAgentAuditEvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(agentauditeventsResource, opts))
}

// Create takes the representation of a agentAuditEvent and creates it.  Returns the server's representation of the agentAuditEvent, and an error, if there is any.
func (c *FakeAgentAuditEvents) Create(ctx context.Context, agentAuditEvent *managementv1.AgentAuditEvent, opts v1.CreateOptions) (result *managementv1.AgentAuditEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(agentauditeventsResource, agentAuditEvent), &managementv1.AgentAuditEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.AgentAuditEvent), err
}

// Update takes the representation of a agentAuditEvent and updates it. Returns the server's representation of the agentAuditEvent, and an error, if there is any.
func (c *FakeAgentAuditEvents) Update(ctx context.Context, agentAuditEvent *managementv1.AgentAuditEvent, opts v1.UpdateOptions) (result *managementv1.AgentAuditEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(agentauditeventsResource, agentAuditEvent), &managementv1.AgentAuditEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.AgentAuditEvent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAgentAuditEvents) UpdateStatus(ctx context.Context, agentAuditEvent *managementv1.AgentAuditEvent, opts v1.UpdateOptions) (*managementv1.AgentAuditEvent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(agentauditeventsResource, "status", agentAuditEvent), &managementv1.AgentAuditEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.AgentAuditEvent), err
}

// Delete takes name of the agentAuditEvent and deletes it. Returns an error if one occurs.
func (c *FakeAgentAuditEvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(agentauditeventsResource, name, opts), &managementv1.AgentAuditEvent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAgentAuditEvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(agentauditeventsResource, listOpts)

	_, err := c.Fake.Invokes(action, &managementv1.AgentAuditEventList{})
	return err
}

// Patch applies the patch and returns the patched agentAuditEvent.
func (c *FakeAgentAuditEvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementv1.AgentAuditEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(agentauditeventsResource, name, pt, data, subresources...), &managementv1.AgentAuditEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.AgentAuditEvent), err
}
