// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	managementv1 "github.com/loft-sh/api/pkg/apis/management/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolicyViolations implements PolicyViolationInterface
type FakePolicyViolations struct {
	Fake *FakeManagementV1
}

var policyviolationsResource = schema.GroupVersionResource{Group: "management.loft.sh", Version: "v1", Resource: "policyviolations"}

var policyviolationsKind = schema.GroupVersionKind{Group: "management.loft.sh", Version: "v1", Kind: "PolicyViolation"}

// Get takes name of the policyViolation, and returns the corresponding policyViolation object, and an error if there is any.
func (c *FakePolicyViolations) Get(ctx context.Context, name string, options v1.GetOptions) (result *managementv1.PolicyViolation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(policyviolationsResource, name), &managementv1.PolicyViolation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.PolicyViolation), err
}

// List takes label and field selectors, and returns the list of PolicyViolations that match those selectors.
func (c *FakePolicyViolations) List(ctx context.Context, opts v1.ListOptions) (result *managementv1.PolicyViolationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(policyviolationsResource, policyviolationsKind, opts), &managementv1.PolicyViolationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &managementv1.PolicyViolationList{ListMeta: obj.(*managementv1.PolicyViolationList).ListMeta}
	for _, item := range obj.(*managementv1.PolicyViolationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested policyViolations.
func (c *FakePolicyViolations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(policyviolationsResource, opts))
}

// Create takes the representation of a policyViolation and creates it.  Returns the server's representation of the policyViolation, and an error, if there is any.
func (c *FakePolicyViolations) Create(ctx context.Context, policyViolation *managementv1.PolicyViolation, opts v1.CreateOptions) (result *managementv1.PolicyViolation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(policyviolationsResource, policyViolation), &managementv1.PolicyViolation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.PolicyViolation), err
}

// Update takes the representation of a policyViolation and updates it. Returns the server's representation of the policyViolation, and an error, if there is any.
func (c *FakePolicyViolations) Update(ctx context.Context, policyViolation *managementv1.PolicyViolation, opts v1.UpdateOptions) (result *managementv1.PolicyViolation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(policyviolationsResource, policyViolation), &managementv1.PolicyViolation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.PolicyViolation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolicyViolations) UpdateStatus(ctx context.Context, policyViolation *managementv1.PolicyViolation, opts v1.UpdateOptions) (*managementv1.PolicyViolation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(policyviolationsResource, "status", policyViolation), &managementv1.PolicyViolation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.PolicyViolation), err
}

// Delete takes name of the policyViolation and deletes it. Returns an error if one occurs.
func (c *FakePolicyViolations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(policyviolationsResource, name), &managementv1.PolicyViolation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolicyViolations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(policyviolationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &managementv1.PolicyViolationList{})
	return err
}

// Patch applies the patch and returns the patched policyViolation.
func (c *FakePolicyViolations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementv1.PolicyViolation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(policyviolationsResource, name, pt, data, subresources...), &managementv1.PolicyViolation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.PolicyViolation), err
}
