// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/api/pkg/client/clientset_generated/clientset/typed/management/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeManagementV1 struct {
	*testing.Fake
}

func (c *FakeManagementV1) Announcements() v1.AnnouncementInterface {
	return &FakeAnnouncements{c}
}

func (c *FakeManagementV1) Clusters() v1.ClusterInterface {
	return &FakeClusters{c}
}

func (c *FakeManagementV1) ClusterAccountTemplates() v1.ClusterAccountTemplateInterface {
	return &FakeClusterAccountTemplates{c}
}

func (c *FakeManagementV1) ClusterConnects() v1.ClusterConnectInterface {
	return &FakeClusterConnects{c}
}

func (c *FakeManagementV1) ClusterRoles() v1.ClusterRoleInterface {
	return &FakeClusterRoles{c}
}

func (c *FakeManagementV1) Configs() v1.ConfigInterface {
	return &FakeConfigs{c}
}

func (c *FakeManagementV1) Features() v1.FeatureInterface {
	return &FakeFeatures{c}
}

func (c *FakeManagementV1) Licenses() v1.LicenseInterface {
	return &FakeLicenses{c}
}

func (c *FakeManagementV1) LicenseTokens() v1.LicenseTokenInterface {
	return &FakeLicenseTokens{c}
}

func (c *FakeManagementV1) LoftRestarts() v1.LoftRestartInterface {
	return &FakeLoftRestarts{c}
}

func (c *FakeManagementV1) LoftUpgrades() v1.LoftUpgradeInterface {
	return &FakeLoftUpgrades{c}
}

func (c *FakeManagementV1) OwnedAccessKeys() v1.OwnedAccessKeyInterface {
	return &FakeOwnedAccessKeys{c}
}

func (c *FakeManagementV1) ResetAccessKeys() v1.ResetAccessKeyInterface {
	return &FakeResetAccessKeys{c}
}

func (c *FakeManagementV1) Selves() v1.SelfInterface {
	return &FakeSelves{c}
}

func (c *FakeManagementV1) SelfSubjectAccessReviews() v1.SelfSubjectAccessReviewInterface {
	return &FakeSelfSubjectAccessReviews{c}
}

func (c *FakeManagementV1) SharedSecrets(namespace string) v1.SharedSecretInterface {
	return &FakeSharedSecrets{c, namespace}
}

func (c *FakeManagementV1) SubjectAccessReviews() v1.SubjectAccessReviewInterface {
	return &FakeSubjectAccessReviews{c}
}

func (c *FakeManagementV1) Teams() v1.TeamInterface {
	return &FakeTeams{c}
}

func (c *FakeManagementV1) Users() v1.UserInterface {
	return &FakeUsers{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeManagementV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
