// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	managementv1 "github.com/loft-sh/api/v3/pkg/apis/management/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualClusterTemplates implements VirtualClusterTemplateInterface
type FakeVirtualClusterTemplates struct {
	Fake *FakeManagementV1
}

var virtualclustertemplatesResource = schema.GroupVersionResource{Group: "management.loft.sh", Version: "v1", Resource: "virtualclustertemplates"}

var virtualclustertemplatesKind = schema.GroupVersionKind{Group: "management.loft.sh", Version: "v1", Kind: "VirtualClusterTemplate"}

// Get takes name of the virtualClusterTemplate, and returns the corresponding virtualClusterTemplate object, and an error if there is any.
func (c *FakeVirtualClusterTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *managementv1.VirtualClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(virtualclustertemplatesResource, name), &managementv1.VirtualClusterTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.VirtualClusterTemplate), err
}

// List takes label and field selectors, and returns the list of VirtualClusterTemplates that match those selectors.
func (c *FakeVirtualClusterTemplates) List(ctx context.Context, opts v1.ListOptions) (result *managementv1.VirtualClusterTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(virtualclustertemplatesResource, virtualclustertemplatesKind, opts), &managementv1.VirtualClusterTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &managementv1.VirtualClusterTemplateList{ListMeta: obj.(*managementv1.VirtualClusterTemplateList).ListMeta}
	for _, item := range obj.(*managementv1.VirtualClusterTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualClusterTemplates.
func (c *FakeVirtualClusterTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(virtualclustertemplatesResource, opts))
}

// Create takes the representation of a virtualClusterTemplate and creates it.  Returns the server's representation of the virtualClusterTemplate, and an error, if there is any.
func (c *FakeVirtualClusterTemplates) Create(ctx context.Context, virtualClusterTemplate *managementv1.VirtualClusterTemplate, opts v1.CreateOptions) (result *managementv1.VirtualClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(virtualclustertemplatesResource, virtualClusterTemplate), &managementv1.VirtualClusterTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.VirtualClusterTemplate), err
}

// Update takes the representation of a virtualClusterTemplate and updates it. Returns the server's representation of the virtualClusterTemplate, and an error, if there is any.
func (c *FakeVirtualClusterTemplates) Update(ctx context.Context, virtualClusterTemplate *managementv1.VirtualClusterTemplate, opts v1.UpdateOptions) (result *managementv1.VirtualClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(virtualclustertemplatesResource, virtualClusterTemplate), &managementv1.VirtualClusterTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.VirtualClusterTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualClusterTemplates) UpdateStatus(ctx context.Context, virtualClusterTemplate *managementv1.VirtualClusterTemplate, opts v1.UpdateOptions) (*managementv1.VirtualClusterTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(virtualclustertemplatesResource, "status", virtualClusterTemplate), &managementv1.VirtualClusterTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.VirtualClusterTemplate), err
}

// Delete takes name of the virtualClusterTemplate and deletes it. Returns an error if one occurs.
func (c *FakeVirtualClusterTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(virtualclustertemplatesResource, name, opts), &managementv1.VirtualClusterTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualClusterTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(virtualclustertemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &managementv1.VirtualClusterTemplateList{})
	return err
}

// Patch applies the patch and returns the patched virtualClusterTemplate.
func (c *FakeVirtualClusterTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementv1.VirtualClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(virtualclustertemplatesResource, name, pt, data, subresources...), &managementv1.VirtualClusterTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*managementv1.VirtualClusterTemplate), err
}
