// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/api/v4/pkg/apis/storage/v1"
	storagev1 "github.com/loft-sh/api/v4/pkg/clientset/versioned/typed/storage/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSlurmInstances implements SlurmInstanceInterface
type fakeSlurmInstances struct {
	*gentype.FakeClientWithList[*v1.SlurmInstance, *v1.SlurmInstanceList]
	Fake *FakeStorageV1
}

func newFakeSlurmInstances(fake *FakeStorageV1, namespace string) storagev1.SlurmInstanceInterface {
	return &fakeSlurmInstances{
		gentype.NewFakeClientWithList[*v1.SlurmInstance, *v1.SlurmInstanceList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("slurminstances"),
			v1.SchemeGroupVersion.WithKind("SlurmInstance"),
			func() *v1.SlurmInstance { return &v1.SlurmInstance{} },
			func() *v1.SlurmInstanceList { return &v1.SlurmInstanceList{} },
			func(dst, src *v1.SlurmInstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.SlurmInstanceList) []*v1.SlurmInstance { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.SlurmInstanceList, items []*v1.SlurmInstance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
